[package]

name = "ejemplo"

version = "0.1.0"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.ht>

[build-dependencies]
cmake = "0.1.48"

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }
cmake = "0.1.48"

